// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/api_gateway/adapters/inbound/grpc/proto/transfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAccount    string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount      string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	AmountCents    int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferCommand) Reset() {
	*x = TransferCommand{}
	mi := &file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCommand) ProtoMessage() {}

func (x *TransferCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCommand.ProtoReflect.Descriptor instead.
func (*TransferCommand) Descriptor() ([]byte, []int) {
	return file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferCommand) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *TransferCommand) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *TransferCommand) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *TransferCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // use string, not uuid type
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto protoreflect.FileDescriptor

const file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDesc = "" +
	"\n" +
	"?internal/api_gateway/adapters/inbound/grpc/proto/transfer.proto\x12\vtransfer.v1\"\x9f\x01\n" +
	"\x0fTransferCommand\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"k\n" +
	"\x10TransferResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2Z\n" +
	"\x0fTransferService\x12G\n" +
	"\bTransfer\x12\x1c.transfer.v1.TransferCommand\x1a\x1d.transfer.v1.TransferResponseBNZLfintech-capstone/m/v2/internal/api_gateway/adapters/inbound/grpc/proto;protob\x06proto3"

var (
	file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescOnce sync.Once
	file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescData []byte
)

func file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescGZIP() []byte {
	file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescOnce.Do(func() {
		file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDesc), len(file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDesc)))
	})
	return file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDescData
}

var file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_goTypes = []any{
	(*TransferCommand)(nil),  // 0: transfer.v1.TransferCommand
	(*TransferResponse)(nil), // 1: transfer.v1.TransferResponse
}
var file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.v1.TransferService.Transfer:input_type -> transfer.v1.TransferCommand
	1, // 1: transfer.v1.TransferService.Transfer:output_type -> transfer.v1.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_init() }
func file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_init() {
	if File_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDesc), len(file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_goTypes,
		DependencyIndexes: file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_depIdxs,
		MessageInfos:      file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_msgTypes,
	}.Build()
	File_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto = out.File
	file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_goTypes = nil
	file_internal_api_gateway_adapters_inbound_grpc_proto_transfer_proto_depIdxs = nil
}
